### ISSUE TITLE
Don't use sleep 

### ISSUE THREAD

**Issue by KaylaMck202** [FB-18-19-PreAP-CS/math-helper-mosgood549#3]
I would just think it would be nicer if either the selection section shows up right away after using a formula, or an output shows up saying something like "would you like to use another formula? (y)es or (n)o" i just thought that might look better.

**Comment by mosgood549** [comment]
I use sleep to make it easier to see the math helper homepage, and it helps the user see the answer without having to scroll through the shell. I think that I'm going to keep it there, because I like the way that it organizes my code.
